name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  project-id: codes.merritt.FeelingFinder

jobs:
  build-flutter-app:
    name: Make
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config cmake ninja-build gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Build Flutter linux version
        working-directory: ${{ github.workspace }}
        run: |
          make
